name: Setup Adobe AIR SDK
author: Josh Tynjala
description: Action to setup Adobe AIR SDK

inputs:
  air-version:
    description: "Version of the Adobe AIR SDK (example: 50.0)"
    required: true
  accept-license:
    description: "Accept the Adobe AIR SDK License Agreement (example: true)"
    required: true
  license-base64:
    description: Use with an encrypted secret to optionally provide a valid adt.lic file, encoded as a Base64 string
    required: false

runs:
  using: "node20"
  main: "main.js"

branding:
  color: "blue"
  icon: "play"
